---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: falco-telegram
  namespace: monitoring
spec:
  encryptedData:
    TELEGRAM_TOKEN: AgAfph2a0T7YlN+Y3pgVeJujTrx6dUxvTOGELj6UM/VDnkwRz0o+/A4kAKne4UYt/w4Szb7B+MQ7ics+4MFg1BEAnPbGSOYFiJ2PvbqcqQOmIdC79xKOpb8tcPfv5IYqgbrZDmC8IhGpvhSXLdOFJcNUo8Nrv2652PwMvgdXKuetX3jS4v9V5oXJyJrPtstS/OmLoqInN013NUEIVMoNu0+hPrDuzslPpy4sIW0XChONFV8cmSGQAk1RNxC38lXfOWycxk36NHtSdCJkhlsq2oHmT0glESpAShdq7mgkeO2M1NN2T//6j1vRjrLSUZIVyNO1QghKdhD6qa3FrWgTHuYeS/6nEME5ewTo+3TogCqQt0S+qKqB79RdFXibh1RaFsHWFZ2cgiIk6okFAbK8EPmHzcIsD11A2+J3yGnIsh3ndlXfamiJc31NfJPywRN7o/lkdP4NMZvO1R0EucRTwsXAiHmfffQ9MRyd3ssY2vDs7QRyum/76b5JhjOwpX8eRcUzihAjEya1xkbQlGFsCP/5AWOiT9H0SUUdXJTe8hN4Hm2ClLVJ3Y509Kn4+dFAJtDXdGC52Ss+po1YmSXrE4N5BXYum6JhvTXm5pyAUKWE22PvSyHVeSasGMVMWH9bKWouI/K6CGYcJ3g3TO4m9P5u+7RYmT4Fkq2tMnCk3gi2H40N4ybqTvd1rTN45sV5XZEm68uDeqdJc4tHYvctJvgv/kHFFLRYKDPSBjHOIC/jTEdpsKBaHneeo9qc4PSl
  template:
    metadata:
      creationTimestamp: null
      name: falco-telegram
      namespace: monitoring
