---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-config
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgB+0VBvIPhobjsUfaOzgOMGuUqA2x7LSHjdn4a9Gh/H1aWuiMGLslDcj3M3ftXbQ5iL0dNj6F66uzuGJCF9CwyDYHP5sJ3ZnkHzU3kD+6v/AFbwquRnVH6/tIMmxDVoxE/cDO4tFzMHB/H6QjBFTlQ4Gotq8p+hXqEbjqQ6AgkY8ViTGUfS+F57PkCngHeA7L8e6+mIjxnY43Eukq4HhY+mAzNjlJGHoN84s04TuTMFl5KcKAu1xcQFtFZSwmfGHjZK7sH9p4AToU5Dl/dZqHxRwXpC38f/+F90V/w6AmdEo7I6KbdYXUH50AvwmM072A/4UoylZnmS+ANFRPpH+i4w2eWJsIGOnirmhsxF4VtgajgSV+Nzsc6PuzXQ634slGMnQN+W4QzPvPi6NaC45SzYV9RPXt/ktaOnTYmGYbhNkGPcH6NWUgi72uQ1rEsuZdlW0D/k1R94GJ7m1POmRqiv82OsZCfxQezimOj6c2A1NxVBElRzurzG9YuqlaCEVZXEozLsiFweUJubMV9M7XthP98uz+EcWrBjFmcZBPM/hKKnl453814i5PtRdF3IKSvrRmk0PSYDpNirZH6VHB00a6tX7lvi3h/4b+jCSYjJBifqVVv0rxy7Cye7XKDZMN9q+hhmALOSUv3JS4YOj5ic1ZylD/hQwETH8Zp1rBcr12+cJfiQ9yA9WSeWmzQ6eV43fg8qJmuLnsMWwtUiV5561aKuk1YFQizzo8S4e8lLrcRrr/NU9IFwFDCIIA3K
  template:
    metadata:
      creationTimestamp: null
      name: telegram-config
      namespace: monitoring
