apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-ci-bot
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-ci-deployer
rules:
- apiGroups: ["apps"]
  resources: ["deployment", "statefulsets"]
  verbs: ["get", "list", "patch", "update", "create", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "patch", "update", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: github-ci-deployer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-ci-deployer
subjects:
  - kind: ServiceAccount
    name: github-ci-bot
    namespace: default
