apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mysql-deployment.yaml
- memcached.yaml
- rabbitmq.yaml
- tomcat.yaml
- nginx.yaml
- sealed-secret.yaml
- network-policy.yaml

configMapGenerator:
- name: mysql-init-config
  files:
  - db_backup.sql
- name: nginx-config
  files:
  - nginx.conf

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext/seccompProfile
        value:
          type: RuntimeDefault
      - op: add
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
  - target:
      kind: Deployment
      name: vprofile-memcached
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
        value: true
  - target:
      kind: Deployment
      name: vprofile-rabbitmq
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
        value: true
  - target:
      kind: Deployment
      name: vprofile-web
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
        value: true
  - target:
      kind: Deployment
      name: vprofile-app
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
        value: true
  - target:
      kind: Deployment
      name: vprofile-db
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
        value: true
