apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile-web
  template:
    metadata:
      labels:
        app: vprofile-web
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.25-alpine
        ports:
        - containerPort: 8080
          name: webport
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: cache
            mountPath: /var/cache/nginx
          - name: tmp
            mountPath: /tmp
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vprofile-web
spec:
  type: ClusterIP
  selector:
    app: vprofile-web
  ports:
  - port: 80
    targetPort: 8080
        
